# Generated by Django 4.0.4 on 2022-05-18 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(blank=True, max_length=25)),
                ('scheduledDate', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('isIssue', models.BooleanField(blank=True)),
                ('severity', models.PositiveSmallIntegerField(blank=True)),
                ('label', models.CharField(max_length=50)),
                ('positionX', models.CharField(max_length=15)),
                ('positionY', models.CharField(max_length=15)),
                ('inspectionId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inspections.inspection')),
            ],
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspectorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inspections.inspector'),
        ),
    ]
