# Generated by Django 4.0.4 on 2022-05-18 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_alter_inspection_city_alter_inspection_scheduleddate_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
